### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by alex3236** [diced/dlauncher#18]
Well, you see, it's been quiet for over a year.

**Comment by SparK-Cruz** [comment]
Hey @diced Are you alive?

**Comment by diced** [comment]
lol I am alive, but I stopped maintaining this as I have other projects I'm working on and busy with other stuff. pretty sure you won't see any updates coming here for a long time.

**Comment by leonardobetti** [comment]
thanks for letting us know. perhaps can we include that you stopped maintaining on the Readme?
