### ISSUE TITLE
Crash on default config

### ISSUE THREAD

**Issue by Diegovsky** [diced/dlauncher#2]
After running the daemon, I did `dlauncher-toggle` and the daemon crashed with the following message:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/launcher/window.rs:159:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The full backtrace has no useful information.

**Comment by diced** [comment]
This is fixed in https://github.com/diced/dlauncher/commit/93bf07584ed5b0c2fffa1ced6a60b24ba9867427!

**Comment by Diegovsky** [comment]
Thanks, it works :)

I'm on wayland btw

**Comment by diced** [comment]
Ah that's probably why the original method didn't work.. Glad it works now though.
