### ISSUE TITLE
Crash upon attempting to type "test" when the window pops up

### ISSUE THREAD

**Issue by MostHated** [diced/dlauncher#3]
Hey there,
    I cloned and built the app, then went to launch it and "test" but then it simply crashed.

```sh
[2022-05-21T17:07:17Z INFO  dlauncher] Started dlauncher
thread 'main' panicked at 'byte index 22 is not a char boundary; it is inside '”' (bytes 21..24) of `“Sigma file manager” is a free, open-source, quickly evolving, modern file manager (explorer / finder) app for Windows, MacOS, and Linux.`', src/fuzzy/mod.rs:69:28
stack backtrace:
```

Thanks,
-MH

**Comment by diced** [comment]
Similar to #1, but no accented character weird..

**Comment by diced** [comment]
Could you send the `.desktop` file of the application in that error (seems to be Sigma File Manager)?

**Comment by diced** [comment]
This should be fixed in https://github.com/diced/dlauncher/commit/e0d4310bba5c7d9a294b988f517830f6a60c1f30!

**Comment by MostHated** [comment]
I was finally able to give this a go, and it looks like everything is good on my end. I appreciate the quick turnaround on the issue. :+1:
