### ISSUE TITLE
Mouse affects app selection even if not moving

### ISSUE THREAD

**Issue by zerowhybr** [diced/dlauncher#8]
Currently, dlauncher gui changes its selected app (after typing an app name) just by having the mouse pointer over it, which in my experience is not a good user experience.

Example: you want to open Vim. You type "vim" and press enter, but your cursor is in the middle of the screen and GiMP was selected, opening GiMP instead of Vim.

I believe that a good way to approach this is to only change the selection if the mouse pointer moves, as that would prevent this kind of issue.

Video that demonstrates the behavior:
[demonstration.webm](https://user-images.githubusercontent.com/50805687/176195828-dce9765a-f304-4c08-b265-9b8a1231fe54.webm)

**Comment by diced** [comment]
Yep, I also get pretty annoyed by this I'll try getting some sort of fix next week or this weekend.

**Comment by diced** [comment]
Fixed in latest commit
